import { Context, Dict, Schema } from 'koishi';
import { SearchObject } from '@koishijs/registry';
import { MarketPerformance, MarketProvider as BaseMarketProvider } from '../shared';
import { type MarketProviderConfig } from './market-internals';
export declare const DEFAULT_ENDPOINT = "https://registry.koishi.t4wefan.pub/index.json";
declare class MarketProvider extends BaseMarketProvider {
    config: MarketProvider.Config;
    private http;
    private failed;
    private scanner;
    private fullCache;
    private tempCache;
    private payload?;
    private endpoint;
    private disposed;
    private serial;
    private dataVersion;
    private contentHash?;
    private forceRefresh;
    private indexMode;
    private cache;
    private router;
    private debugInfo?;
    private backgroundTask?;
    private backgroundSerial?;
    private pendingRefreshTask?;
    private warmDiskCacheTask?;
    private flushData;
    constructor(ctx: Context, config?: MarketProvider.Config);
    start(refresh?: boolean): Promise<void>;
    collect(): Promise<any>;
    private createScanner;
    private hasCurrentMarketData;
    private startSoftRefresh;
    get(): Promise<{
        registry: string;
        failed: number;
        total: number;
        progress: number;
        gravatar: string;
        stale: boolean;
        error: string;
        cached: boolean;
        cachedAt: number;
        validatedAt: number;
        serverNow: number;
        refreshing: boolean;
        loading: boolean;
        dataVersion: number;
        debug: MarketPerformance;
    }>;
    getSnapshot(): Promise<{
        registry: string;
        data: Dict<SearchObject>;
        dataVersion: number;
        failed: number;
        total: number;
        progress: number;
        gravatar: string;
        stale: boolean;
        error: any;
        cached: boolean;
        cachedAt: number;
        validatedAt: number;
        serverNow: number;
        refreshing: boolean;
        loading: boolean;
        debug: MarketPerformance;
    } | {
        serverNow: number;
        debug: MarketPerformance;
        registry?: string;
        data?: Dict<SearchObject>;
        dataVersion?: number;
        total: number;
        failed: number;
        progress: number;
        gravatar?: string;
        stale?: boolean;
        error?: string;
        cached?: boolean;
        cachedAt?: number;
        validatedAt?: number;
        refreshing?: boolean;
        loading?: boolean;
    }>;
    private createPayload;
    private refreshAfterPrepare;
    private applyIndex;
    private applyDiskCache;
    private warmDiskCache;
    private loadDiskCache;
    private refreshInBackground;
    private notifyMarketRefresh;
    private refreshIndexInBackground;
    private probeIndexInBackground;
    probeInBackground(reason?: string): Promise<boolean>;
    private updateDebugInfo;
    private getDebugInfo;
    private isStale;
    private log;
}
declare namespace MarketProvider {
    interface Config extends MarketProviderConfig {
    }
    const Config: Schema<Config>;
}
export default MarketProvider;
