import { Context, Dict, Schema } from 'koishi';
import { SearchObject } from '@koishijs/registry';
import { MarketPerformance, MarketProvider as BaseMarketProvider } from '../shared';
export declare const DEFAULT_ENDPOINT = "https://registry.koishi.t4wefan.pub/index.json";
declare const logLevels: readonly ["silent", "error", "warn", "info", "debug"];
type LogLevel = typeof logLevels[number];
declare class MarketProvider extends BaseMarketProvider {
    config: MarketProvider.Config;
    private http;
    private failed;
    private scanner;
    private fullCache;
    private tempCache;
    private payload?;
    private endpoint;
    private disposed;
    private serial;
    private forceRefresh;
    private indexMode;
    private cacheFile;
    private cacheDir;
    private cacheEntries;
    private cacheMeta?;
    private conditionMeta?;
    private cacheResult?;
    private debugInfo?;
    private routeStats;
    private backgroundTask?;
    private backgroundSerial?;
    private pendingRefreshTask?;
    private cacheWriteTimer?;
    private routeStatsWriteTimer?;
    private warmDiskCacheTask?;
    private pendingControllers;
    private flushData;
    constructor(ctx: Context, config?: MarketProvider.Config);
    start(refresh?: boolean): Promise<void>;
    collect(): Promise<any>;
    private createScanner;
    private hasCurrentMarketData;
    private startSoftRefresh;
    private fetchIndex;
    private fetchIndexFromEndpoints;
    private getRescueEndpoints;
    private getEndpointCandidates;
    private getEndpoints;
    private getPreferredEndpoint;
    private waitRouteTurn;
    private getRouteScore;
    private recordRouteSuccess;
    private recordRouteFailure;
    private getRouteScores;
    private isRouteCoolingDown;
    private clearRouteCooldowns;
    private getConditionalHeaders;
    private updateCacheState;
    private fetchEndpoint;
    get(): Promise<{
        registry: string;
        data: Dict<SearchObject>;
        failed: number;
        total: number;
        progress: number;
        gravatar: string;
        stale: boolean;
        error: any;
        cached: boolean;
        cachedAt: number;
        validatedAt: number;
        serverNow: number;
        refreshing: boolean;
        loading: boolean;
        debug: MarketPerformance;
    } | {
        serverNow: number;
        debug: MarketPerformance;
        registry?: string;
        data: Dict<SearchObject>;
        total: number;
        failed: number;
        progress: number;
        gravatar?: string;
        stale?: boolean;
        error?: string;
        cached?: boolean;
        cachedAt?: number;
        validatedAt?: number;
        refreshing?: boolean;
        loading?: boolean;
    }>;
    private createPayload;
    private refreshAfterPrepare;
    private applyIndex;
    private applyDiskCache;
    private warmDiskCache;
    private loadDiskCache;
    private pickDiskCache;
    private loadCacheEntryResult;
    private getCacheScore;
    private getCacheEntryFilename;
    private createSplitCacheEntry;
    private writeCacheEntryFile;
    private pruneSplitCacheFiles;
    private scheduleDiskCacheWrite;
    private scheduleRouteStatsWrite;
    private writeRouteStatsCache;
    private serializeRouteStats;
    private pruneCacheEntries;
    private writeDiskCache;
    private refreshInBackground;
    private notifyMarketRefresh;
    private refreshIndexInBackground;
    private probeIndexInBackground;
    probeInBackground(reason?: string): Promise<boolean>;
    private updateDebugInfo;
    private getDebugInfo;
    private isStale;
    private trackController;
    private untrackControllers;
    private abortPendingRequests;
    private isInternalAbort;
    private log;
}
declare namespace MarketProvider {
    interface Config {
        endpoint?: string;
        timeout?: number;
        proxyAgent?: string;
        autoRoute?: boolean;
        logLevel?: LogLevel;
    }
    const Config: Schema<Config>;
}
export default MarketProvider;
