import { Context, Dict, HTTP } from 'koishi';
import { DependencyMetaKey, Registry, RemotePackage } from '@koishijs/registry';
import { type RegistryStatus } from '../shared';
import { type InstallFallbackCandidate, type InstallerConfig } from './installer-types';
export declare class RegistryMetadata {
    private ctx;
    private config;
    http: HTTP;
    endpoint: string;
    fullCache: Dict<Dict<Pick<RemotePackage, DependencyMetaKey>>>;
    registryStatus: Dict<RegistryStatus>;
    tempCache: Dict<Dict<Pick<RemotePackage, DependencyMetaKey>>>;
    private pkgTasks;
    private metadataEndpoint;
    private routeProbeTask?;
    private routeProbeResult?;
    private routeStats;
    private notFoundCache;
    private statsFile;
    private statsWriteTimer?;
    private flushData;
    private tempRegistryStatus;
    private flushRegistryStatus;
    private pendingControllers;
    private currentSerial;
    constructor(ctx: Context, config: InstallerConfig);
    get serial(): number;
    get selectedEndpoint(): string;
    get hasRouteProbeResult(): boolean;
    restoreRouteStats(): Promise<void>;
    initializeEndpoint(): Promise<void>;
    reset(reason: string): Promise<void>;
    dispose(): void;
    hasRecentNotFound(name: string): boolean;
    ensureEndpoint(name: string, serial?: number): Promise<void>;
    getRegistry(name: string, serial?: number): Promise<Registry>;
    setPackage(name: string, versions: RemotePackage[]): void;
    getPackage(name: string): Promise<any>;
    getInstallFallbackCandidate(failedEndpoint?: string): InstallFallbackCandidate | undefined;
    isStale(serial: number): boolean;
    formatError(error: any): Required<Pick<RegistryStatus, 'reason' | 'error'>>;
    private createHttp;
    private loadRouteStats;
    private scheduleStatsWrite;
    private resetEndpoint;
    private getRegistryEndpoints;
    private getPreferredMetadataEndpoint;
    private getRegistryEndpointCandidates;
    private getRouteProbeEndpoints;
    private raceEndpoints;
    private probeMetadataEndpoint;
    private fetchRegistryEndpoint;
    private applyRouteProbeResult;
    private waitRouteTurn;
    private getRouteScore;
    private recordRouteSuccess;
    private recordRouteFailure;
    private getFallbackDelay;
    private getRouteScores;
    private fetchRegistryByRoute;
    private setRegistryStatus;
    private clearRegistryStatus;
    private fetchPackage;
    private trackController;
    private untrackControllers;
    private abortPendingRequests;
    private isInternalAbort;
}
