import { Context, Dict, HTTP } from 'koishi';
import { DependencyMetaKey, Registry, RemotePackage } from '@koishijs/registry';
import { type RegistryStatus } from '../shared';
import { type InstallFallbackCandidate, type InstallerConfig } from './installer-types';
export declare class RegistryMetadata {
    private ctx;
    private config;
    fullCache: Dict<Dict<Pick<RemotePackage, DependencyMetaKey>>>;
    registryStatus: Dict<RegistryStatus>;
    tempCache: Dict<Dict<Pick<RemotePackage, DependencyMetaKey>>>;
    private pkgTasks;
    private router;
    private notFoundCache;
    private tempRegistryStatus;
    private flushData;
    private flushRegistryStatus;
    constructor(ctx: Context, config: InstallerConfig);
    get http(): HTTP;
    get endpoint(): string;
    get serial(): number;
    get selectedEndpoint(): string;
    get hasRouteProbeResult(): boolean;
    restoreRouteStats(): Promise<void>;
    initializeEndpoint(): Promise<void>;
    reset(reason: string): Promise<void>;
    dispose(): void;
    hasRecentNotFound(name: string): boolean;
    ensureEndpoint(name: string, serial?: number): Promise<void>;
    getRegistry(name: string, serial?: number): Promise<Registry>;
    setPackage(name: string, versions: RemotePackage[]): void;
    getPackage(name: string): Promise<any>;
    getInstallFallbackCandidate(failedEndpoint?: string): InstallFallbackCandidate | undefined;
    isStale(serial: number): boolean;
    formatError(error: any): Required<Pick<RegistryStatus, 'reason' | 'error'>>;
    private setRegistryStatus;
    private clearRegistryStatus;
    private fetchPackage;
}
